# Generated by Django 4.1.7 on 2023-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_kontakt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
