# Generated by Django 4.1.7 on 2023-11-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_alter_kontakt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_kontakt', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
