# Generated by Django 4.1.7 on 2023-11-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_kontakt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='user',
        ),
    ]
