# Generated by Django 4.1.7 on 2023-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_educations_experience_projects_service_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(default=' ', upload_to='cv'),
            preserve_default=False,
        ),
    ]
