# Generated by Django 4.1.7 on 2023-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(help_text='Upload Your CV', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='year',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.IntegerField(max_length=100),
        ),
    ]
