# Generated by Django 4.1.7 on 2023-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_cv_alter_educations_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('massage', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='educations',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-year',)},
        ),
    ]
